version = 0.1
[default.deploy.parameters]
stack_name = "yd-ai-bff-sam"
resolve_s3 = true
s3_prefix = "yd-ai-bff-sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
 